"""
SQLAlchemy 2.0 declarative base and reusable mixins.

All models inherit from Base.
UUIDPrimaryKeyMixin: provides a UUID primary key generated by the application.
TimestampMixin: provides created_at and updated_at timestamps.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, String, event, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Base class for all SQLAlchemy models.
    Using DeclarativeBase from SQLAlchemy 2.0 (type-annotated style).
    """
    pass


@event.listens_for(Base, "init", propagate=True)
def _apply_column_defaults(target, args, kwargs):
    """
    Apply Python-level column defaults at object construction time.

    SQLAlchemy's column `default=` is normally only applied right before
    INSERT — not when you construct a Python object.  This listener fires
    on every `__init__` and fills in any column whose value was not supplied
    as a keyword argument, making unit-tests possible without a DB round-trip.
    """
    mapper = target.__class__.__mapper__
    for col_attr in mapper.column_attrs:
        for col in col_attr.columns:
            if col.name in kwargs:
                continue  # caller provided an explicit value
            if col.default is None:
                continue  # no default defined
            default = col.default
            if default.is_scalar:
                kwargs[col.name] = default.arg
            elif default.is_callable:
                # callable defaults receive an ExecutionContext; pass {} for tests
                kwargs[col.name] = default.arg({})


class UUIDPrimaryKeyMixin:
    """
    Provides a UUID primary key generated by the Python application.
    Using String(36) for compatibility — avoids native UUID type
    differences between PostgreSQL and SQLite (used in tests).
    """
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True,
    )


class TimestampMixin:
    """
    Adds created_at and updated_at to any model.
    Both are UTC timestamps set automatically.
    updated_at is updated on every UPDATE statement.
    """
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
